// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojazyxzbasabzxmuymdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qYXp5eHpiYXNhYnp4bXV5bWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTg3NzEsImV4cCI6MjA3Mzg3NDc3MX0.-cOFwM54d2z6cFNEgc0c1tRnVx2dFdT_tuid3RSeENs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});